---
title: "FlightsOverYear_LaPell"
author: "Joseph LaPell"
date: "2022-09-27"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(here)
```

Loading flight data into variables

```{r}
df17 = read_csv(here("data_raw", "airline_data_2017.zip"))
df18 = read_csv(here("data_raw", "airline_data_2018.zip"))
df19 = read_csv(here("data_raw", "airline_data_2019.zip"))
df20 = read_csv(here("data_raw", "airline_data_2020.zip"))
df21 = read_csv(here("data_raw", "airline_data_2021.zip"))
df22 = read_csv(here("data_raw", "airline_data_2022.zip"))
```

Filtering dataframes to only include flights from Southwest, and then using piping operator to graph total departures per month.

```{r}
sw17 <- filter(df17, CARRIER_NAME == "Southwest Airlines Co.")  
  sw17 %>% ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2017") + 
  xlab("Month") + ylab("Total Departures")

sw18 <- filter(df18, CARRIER_NAME == "Southwest Airlines Co.")
  sw18 %>% ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2018") + 
  xlab("Month") + ylab("Total Departures")

sw19 <- filter(df19, CARRIER_NAME == "Southwest Airlines Co.") 
  sw19 %>%ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2019") + 
  xlab("Month") + ylab("Total Departures")

sw20 <- filter(df20, CARRIER_NAME == "Southwest Airlines Co.") 
  sw20 %>% ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2020") + 
  xlab("Month") + ylab("Total Departures")

sw21 <- filter(df21, CARRIER_NAME == "Southwest Airlines Co.") 
  sw21 %>% ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2021") + 
  xlab("Month") + ylab("Total Departures")

sw22 <- filter(df22, CARRIER_NAME == "Southwest Airlines Co.") 
  sw22 %>%ggplot(aes(x = MONTH)) + geom_bar(aes(weight = DEPARTURES_PERFORMED)) + ggtitle("SWAir Departures 2022(Up to June)") + 
  xlab("Month") + ylab("Total Departures")
```

```{r}
combined <-  rbind(sw17,sw18,sw19,sw20,sw21,sw22) 
combined %>% mutate()
```


